const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const qs=(s)=>document.querySelector(s);const qsa=(s)=>[...document.querySelectorAll(s)];
// Scroll changes the cover, not the presenter’s position or control of the page.
let scrollQueued=false;function updateScroll(){scrollQueued=false;const cover=qs('.cover');const y=window.scrollY;const fraction=Math.min(1,y/(cover.offsetHeight*.7));qs('.masthead').classList.toggle('scrolled',y>40);qs('.reading-progress').style.transform=`scaleX(${Math.min(1,y/Math.max(1,document.documentElement.scrollHeight-window.innerHeight))})`;qs('.cover-content').style.opacity=reduceMotion.matches?'1':String(1-fraction);qs('.cover-content').style.transform=reduceMotion.matches?'none':`translateY(${fraction*60}px) scale(${1-fraction*.06})`}
window.addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateScroll)}},{passive:true});window.addEventListener('resize',updateScroll);reduceMotion.addEventListener('change',updateScroll);updateScroll();
qsa('[data-heat]').forEach(button=>button.addEventListener('click',()=>{const focus=button.dataset.heat==='opportunity';qsa('[data-heat]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));qs('.occupancy-board').classList.toggle('focus-opportunity',focus);qs('#opportunity-copy').textContent=focus?'Target the quieter slots. Protect the value of peak time.':'The opportunity is already in your customer base.'}));
const audiences={corporates:['Corporates','Enquiry → team day → repeat company event','Company details and event enquiries identify the organiser.'],players:['Serious players','Regular play → coaching → competitive sessions','Declared goals and session history guide relevant recommendations.'],social:['Socialisers','First social → community → regular daytime play','Social participation and stated availability guide the invitation.'],families:['Families','Family visit → holiday session → junior programme','Parent preferences connect the family to suitable activities.'],juniors:['Juniors','Junior session → progression → next programme','Messages go to the parent or guardian, matched to suitable programmes.']};
qsa('[data-audience]').forEach(button=>button.addEventListener('click',()=>{const a=audiences[button.dataset.audience];qsa('[data-audience]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));qs('#example-audience').textContent=a[0];qs('#example-journey').textContent=a[1];qs('#example-detail').textContent=a[2];if(!reduceMotion.matches)qs('.audience-example').animate([{opacity:.35,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,easing:'cubic-bezier(.16,1,.3,1)'})}));
const stages=[
{title:'Start with a relevant invitation.',description:'Match the session to the customer’s interests and availability.',score:20},
{title:'An invitation, at the right time.',description:'A personalised email introduces a suitable weekday session.',score:20},
{title:'The customer replies.',description:'Their reply tells your team when they can play.',score:20},
{title:'+10 points. A warmer conversation.',description:'A positive reply raises engagement and prompts personal follow-up.',score:30},
{title:'+50 points. The booking changes the journey.',description:'Stop the rebooking chase. Move into post-visit care and relevant next steps.',score:80}
];
let stage=0,running=false,timer=null,usedJourney=false;const play=qs('#play-journey');const playIcon=play.querySelector('svg').outerHTML;function labelPlay(text){play.innerHTML=playIcon+text}function cancelTimer(){if(timer!==null){clearTimeout(timer);timer=null}}function stopJourney(){running=false;cancelTimer();labelPlay(stage===4?'Replay journey':'Play the journey')}
function setStage(n){const previous=stage;stage=Math.min(4,Math.max(0,n));qs('.journey-theatre').dataset.stage=String(stage);qsa('[data-node]').forEach((node,index)=>{node.classList.toggle('active',stage===index+1);node.classList.toggle('complete',stage>index+1)});qs('#email-bubble').classList.toggle('revealed',stage>=1);qs('#reply-bubble').classList.toggle('revealed',stage>=2);qs('#message-result').classList.toggle('revealed',stage>=4);qs('#score-value').textContent=String(stages[stage].score);qs('.ring-value').style.strokeDashoffset=String(477.522*(1-stages[stage].score/100));qs('#stage-title').textContent=stages[stage].title;qs('#stage-description').textContent=stages[stage].description;qs('#next-step').disabled=stage===4;const pop=qs('#points-pop');pop.classList.remove('pop');if(stage>=3&&previous!==stage){pop.textContent=stage===3?'+10':'+50';if(!reduceMotion.matches){void pop.offsetWidth;pop.classList.add('pop')}}const traveller=qs('.traveller');traveller.classList.remove('fly');if(stage===1&&!reduceMotion.matches){traveller.style.setProperty('--travel',qs('.journey-nodes').clientWidth*.25+'px');void traveller.offsetWidth;traveller.classList.add('fly')}}
function continueJourney(){cancelTimer();if(!running)return;if(stage>=4){stopJourney();return}timer=setTimeout(()=>{setStage(stage+1);continueJourney()},stage===1?1500:stage===2?1300:2000)}
function startJourney(){usedJourney=true;if(stage>=4)setStage(0);running=true;labelPlay('Pause journey');if(stage===0)setStage(1);continueJourney()}
play.addEventListener('click',()=>{usedJourney=true;running?stopJourney():startJourney()});qs('#next-step').addEventListener('click',()=>{usedJourney=true;stopJourney();setStage(stage+1);labelPlay(stage===4?'Replay journey':'Play the journey')});qs('#reset-journey').addEventListener('click',()=>{usedJourney=true;stopJourney();setStage(0);labelPlay('Play the journey')});setStage(0);
if('IntersectionObserver'in window){const autoDemo=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&!usedJourney&&!reduceMotion.matches){startJourney()}else if(!entry.isIntersecting&&running)stopJourney()}},{threshold:.5});autoDemo.observe(qs('.journey-theatre'))}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopJourney()});reduceMotion.addEventListener('change',()=>{if(reduceMotion.matches)stopJourney()});

const icons={"briefcase": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"M8 7V4h8v3M3 12c6 4 12 4 18 0M10 13h4\"/>", "trophy": "<path d=\"M8 3h8v6a4 4 0 0 1-8 0V3ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 1v5m-5 3h10m-8 0v-3h6v3\"/>", "users": "<circle cx=\"9\" cy=\"8\" r=\"3\"/><path d=\"M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5\"/>", "family": "<circle cx=\"6\" cy=\"6\" r=\"2\"/><circle cx=\"18\" cy=\"6\" r=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"2\"/><path d=\"M2 18v-4a4 4 0 0 1 8 0m4 0a4 4 0 0 1 8 0v4M8 22v-3a4 4 0 0 1 8 0v3\"/>", "junior": "<circle cx=\"12\" cy=\"6\" r=\"3\"/><path d=\"M5 12h14m-7-3v8m0 0-5 5m5-5 5 5\"/>", "database": "<ellipse cx=\"12\" cy=\"5\" rx=\"8\" ry=\"3\"/><path d=\"M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0\"/>", "mail": "<rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"3\"/><path d=\"m2 7 10 7L22 7\"/>", "chat": "<path d=\"M21 11a9 9 0 0 1-9 9 10 10 0 0 1-4-1l-6 2 2-6a9 9 0 1 1 17-4Z\"/><path d=\"M8 10h8m-8 4h5\"/>", "calendar": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"17\" rx=\"2\"/><path d=\"M7 2v6m10-6v6M3 11h18m-14 5 3 3 6-6\"/>", "spark": "<path d=\"m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z\"/>", "star": "<path d=\"m12 2 3.1 6.3 6.9 1-5 4.9 1.2 6.9-6.2-3.3-6.2 3.3L7 14.2 2 9.3l6.9-1Z\"/>", "phone": "<path d=\"M7 3 3 5c-1 8 8 17 16 16l2-4-5-4-3 3-5-5 3-3Z\"/>", "globe": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><ellipse cx=\"12\" cy=\"12\" rx=\"4\" ry=\"10\"/><path d=\"M2 12h20\"/>", "camera": "<rect x=\"2\" y=\"6\" width=\"20\" height=\"15\" rx=\"3\"/><path d=\"m7 6 2-3h6l2 3\"/><circle cx=\"12\" cy=\"13\" r=\"4\"/>", "mobile": "<rect x=\"6\" y=\"2\" width=\"12\" height=\"20\" rx=\"3\"/><path d=\"M10 5h4m-3 14h2\"/>", "chart": "<path d=\"M3 3v18h19M7 16l5-5 4 2 6-8m-5 0h5v5\"/>", "window": "<rect x=\"2\" y=\"3\" width=\"20\" height=\"18\" rx=\"2\"/><path d=\"M2 8h20M6 5.5h.01M10 5.5h.01M6 12h6m-6 4h12\"/>", "bot": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"14\" rx=\"4\"/><path d=\"M12 3v4M8 17h8M7 12h.01M17 12h.01\"/><circle cx=\"12\" cy=\"2\" r=\"1\"/>", "arrow": "<path d=\"M4 12h16m-6-6 6 6-6 6\"/>", "check": "<path d=\"m5 12 4 4L19 6\"/>", "play": "<path d=\"m8 4 13 8-13 8Z\"/>", "growth": "<path d=\"M4 19h16M7 15V9m5 6V5m5 10V2\"/>", "link": "<path d=\"m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0\"/>", "heart": "<path d=\"M20 4a5 5 0 0 0-8 2 5 5 0 0 0-8-2c-5 5 2 11 8 17 6-6 13-12 8-17Z\"/>", "shield": "<path d=\"m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Zm-5 10 3 3 7-7\"/>"};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`}
const systems={whatsapp:{steps:[['users','Grow the community','Invitations & join links'],['chat','Personal follow-up','Automated 1:1 messages'],['calendar','Bring people back','Sessions, socials & events']],summary:'Community content, supported by relevant messages to opted-in members.',note:'CRM automation sends to individuals. Your team posts into WhatsApp groups and Community announcements.'},reviews:{steps:[['calendar','Completed visit','Eligible customer'],['mail','Review invitation','Automated follow-up'],['star','Google review','An honest experience']],summary:'Ask at the right moment, without asking after every visit.',note:'Use verified completion or agreed booking-status rules. Exclude cancellations; no incentives or sentiment-based review filtering.'},phone:{steps:[['globe','Website & Google','Your business number'],['phone','CRM call routing','A visible call record'],['mobile','Your mobile rings','Or your chosen staff']],summary:'A professional club number. The same phone in your pocket.',note:'Number availability and verification are checked at setup. Rental, forwarding and call usage are additional.'}};
function systemMarkup(s){return s.steps.map(([ic,title,sub])=>`<div class="diagram-stop">${icon(ic)}<h3>${title}</h3><p>${sub}</p></div>`).join('<span class="system-arrow" aria-hidden="true">→</span>')}
const systemTabs=qsa('[data-system]');function selectSystem(key,focus=false){const s=systems[key];systemTabs.forEach(t=>{const on=t.dataset.system===key;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;if(on&&focus)t.focus()});qs('#system-panel').setAttribute('aria-labelledby','system-tab-'+key);qs('#system-steps').innerHTML=systemMarkup(s);qs('#system-summary').textContent=s.summary;qs('#system-note').textContent=s.note}
systemTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectSystem(tab.dataset.system));tab.addEventListener('keydown',e=>{let next=index;if(e.key==='ArrowRight')next=(index+1)%systemTabs.length;else if(e.key==='ArrowLeft')next=(index+systemTabs.length-1)%systemTabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=systemTabs.length-1;else return;e.preventDefault();selectSystem(systemTabs[next].dataset.system,true)})});
// All three club systems are available in a print copy, not just the selected tab.
for(const key of ['reviews','phone']){const s=systems[key];const p=document.createElement('div');p.className='print-system';p.innerHTML=`<h3>${key==='reviews'?'Review generation':'Business number'}</h3><div class="system-steps">${systemMarkup(s)}</div><p class="footnote">${s.note}</p>`;qs('#system-panel').after(p)}
let openBeforePrint=[],stageBeforePrint=0,systemBeforePrint='whatsapp';window.addEventListener('beforeprint',()=>{stopJourney();stageBeforePrint=stage;setStage(4);systemBeforePrint=qs('[data-system][aria-selected=true]').dataset.system;selectSystem('whatsapp');openBeforePrint=qsa('details').filter(d=>d.open);qsa('details').forEach(d=>d.open=true)});window.addEventListener('afterprint',()=>{setStage(stageBeforePrint);selectSystem(systemBeforePrint);qsa('details').forEach(d=>d.open=openBeforePrint.includes(d))});qs('#print').addEventListener('click',()=>window.print());
